name: CI
on: [push, pull_request]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: antongolub/action-setup-bun@v1
        with:
          cache: true
          cache-bin: true

      - name: Install deps
        run: bun install

      - name: Run test
        run: bun run test
